
# This file is automatically generated, you probably don't want to edit this

wellPlateOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wellPlateOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            wellID = NULL,
            rowVar = NULL,
            colVar = NULL,
            value = NULL,
            plateSize = "96",
            shape = "circle",
            colourScheme = "viridis",
            showLegend = TRUE,
            crossMissing = FALSE,
            showBorder = TRUE,
            wellSize = 0.85, ...) {

            super$initialize(
                package="jwellplate",
                name="wellPlate",
                requiresData=TRUE,
                ...)

            private$..wellID <- jmvcore::OptionVariable$new(
                "wellID",
                wellID,
                suggested=list(
                    "nominal",
                    "id",
                    "continuous"),
                permitted=list(
                    "factor",
                    "id",
                    "numeric"))
            private$..rowVar <- jmvcore::OptionVariable$new(
                "rowVar",
                rowVar,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "factor",
                    "id"))
            private$..colVar <- jmvcore::OptionVariable$new(
                "colVar",
                colVar,
                suggested=list(
                    "continuous",
                    "nominal"),
                permitted=list(
                    "factor",
                    "id",
                    "numeric"))
            private$..value <- jmvcore::OptionVariable$new(
                "value",
                value,
                suggested=list(
                    "continuous",
                    "nominal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..plateSize <- jmvcore::OptionList$new(
                "plateSize",
                plateSize,
                options=list(
                    "6",
                    "12",
                    "24",
                    "96",
                    "384",
                    "1536"),
                default="96")
            private$..shape <- jmvcore::OptionList$new(
                "shape",
                shape,
                options=list(
                    "circle",
                    "rect"),
                default="circle")
            private$..colourScheme <- jmvcore::OptionList$new(
                "colourScheme",
                colourScheme,
                options=list(
                    "viridis",
                    "magma",
                    "plasma",
                    "cividis",
                    "reds",
                    "blues"),
                default="viridis")
            private$..showLegend <- jmvcore::OptionBool$new(
                "showLegend",
                showLegend,
                default=TRUE)
            private$..crossMissing <- jmvcore::OptionBool$new(
                "crossMissing",
                crossMissing,
                default=FALSE)
            private$..showBorder <- jmvcore::OptionBool$new(
                "showBorder",
                showBorder,
                default=TRUE)
            private$..wellSize <- jmvcore::OptionNumber$new(
                "wellSize",
                wellSize,
                min=0.1,
                max=1,
                default=0.85)

            self$.addOption(private$..wellID)
            self$.addOption(private$..rowVar)
            self$.addOption(private$..colVar)
            self$.addOption(private$..value)
            self$.addOption(private$..plateSize)
            self$.addOption(private$..shape)
            self$.addOption(private$..colourScheme)
            self$.addOption(private$..showLegend)
            self$.addOption(private$..crossMissing)
            self$.addOption(private$..showBorder)
            self$.addOption(private$..wellSize)
        }),
    active = list(
        wellID = function() private$..wellID$value,
        rowVar = function() private$..rowVar$value,
        colVar = function() private$..colVar$value,
        value = function() private$..value$value,
        plateSize = function() private$..plateSize$value,
        shape = function() private$..shape$value,
        colourScheme = function() private$..colourScheme$value,
        showLegend = function() private$..showLegend$value,
        crossMissing = function() private$..crossMissing$value,
        showBorder = function() private$..showBorder$value,
        wellSize = function() private$..wellSize$value),
    private = list(
        ..wellID = NA,
        ..rowVar = NA,
        ..colVar = NA,
        ..value = NA,
        ..plateSize = NA,
        ..shape = NA,
        ..colourScheme = NA,
        ..showLegend = NA,
        ..crossMissing = NA,
        ..showBorder = NA,
        ..wellSize = NA)
)

wellPlateResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wellPlateResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Well Plate Map")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Plate Map",
                width=750,
                height=520,
                renderFun=".plot",
                requiresData=TRUE,
                clearWith=list(
                    "wellID",
                    "rowVar",
                    "colVar",
                    "value",
                    "plateSize",
                    "shape",
                    "colourScheme",
                    "showLegend",
                    "crossMissing",
                    "showBorder",
                    "wellSize")))}))

wellPlateBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wellPlateBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jwellplate",
                name = "wellPlate",
                version = c(1,0,0),
                options = options,
                results = wellPlateResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Well Plate Map
#'
#' Draws a coloured plate map (6/12/24/96/384/1536 wells) from plate-based 
#' experimental data.
#' @param data .
#' @param wellID a single variable holding well identifiers such as "A1" or
#'   "A01", or a plain 1-based well number (e.g. 1-96 for a 96-well plate,
#'   numbered row-major starting at the top-left well). Leave blank and use
#'   rowVar/colVar instead if your data has separate row and column columns.
#' @param rowVar a variable holding the row of each well (e.g. "A", "B", ...).
#' @param colVar a variable holding the column number of each well (e.g. 1, 2,
#'   ...).
#' @param value the variable to display in each well. Numeric variables are
#'   shown with a continuous colour scale + colourbar; nominal (categorical)
#'   variables are shown with a discrete legend.
#' @param plateSize the number of wells on the plate.
#' @param shape .
#' @param colourScheme colour scale used for numeric data. Ignored for
#'   categorical data.
#' @param showLegend .
#' @param crossMissing .
#' @param showBorder .
#' @param wellSize size of each well relative to the grid spacing (0.1-1).
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
wellPlate <- function(
    data,
    wellID,
    rowVar,
    colVar,
    value,
    plateSize = "96",
    shape = "circle",
    colourScheme = "viridis",
    showLegend = TRUE,
    crossMissing = FALSE,
    showBorder = TRUE,
    wellSize = 0.85) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("wellPlate requires jmvcore to be installed (restart may be required)")

    if ( ! missing(wellID)) wellID <- jmvcore::resolveQuo(jmvcore::enquo(wellID))
    if ( ! missing(rowVar)) rowVar <- jmvcore::resolveQuo(jmvcore::enquo(rowVar))
    if ( ! missing(colVar)) colVar <- jmvcore::resolveQuo(jmvcore::enquo(colVar))
    if ( ! missing(value)) value <- jmvcore::resolveQuo(jmvcore::enquo(value))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(wellID), wellID, NULL),
            `if`( ! missing(rowVar), rowVar, NULL),
            `if`( ! missing(colVar), colVar, NULL),
            `if`( ! missing(value), value, NULL))


    options <- wellPlateOptions$new(
        wellID = wellID,
        rowVar = rowVar,
        colVar = colVar,
        value = value,
        plateSize = plateSize,
        shape = shape,
        colourScheme = colourScheme,
        showLegend = showLegend,
        crossMissing = crossMissing,
        showBorder = showBorder,
        wellSize = wellSize)

    analysis <- wellPlateClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

